# Generated by Django 5.0.7 on 2024-09-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('scope_from', models.DateField(blank=True, null=True)),
                ('scope_to', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
