# Generated by Django 5.0.7 on 2024-09-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kensist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(choices=[('CIOX', 'CIOX'), ('Centine', 'Centine')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
