# Generated by Django 5.0.7 on 2024-09-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kensist', '0003_alter_project_scope_from_alter_project_scope_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='vname',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
