# Generated by Django 5.0.7 on 2024-09-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kensist', '0004_project_vname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='vname',
            new_name='version',
        ),
    ]
