# Generated by Django 5.1 on 2024-10-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_rename_postal_code_address_zip_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='zip_code',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='street_address',
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
