# Generated by Django 5.1 on 2024-10-02 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_rename_zip_code_address_postal_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street_address',
            new_name='street',
        ),
    ]
