# Generated by Django 5.1 on 2024-10-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_user_driving_license_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='driving_license_no',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
