# Generated by Django 5.1 on 2024-10-05 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_user_fcm_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fcm_token',
        ),
    ]
