# Generated by Django 5.0 on 2023-12-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Items',
            new_name='Items',
        ),
    ]
