# Generated by Django 4.2.7 on 2023-12-07 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_product_items_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='item_name',
            new_name='itehjjm_name',
        ),
    ]
