# Generated by Django 4.2.7 on 2023-12-07 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_item_name_items_itehjjm_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='itehjjm_name',
            new_name='item_name',
        ),
    ]
