# Generated by Django 5.1 on 2024-10-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration_in_hours',
            field=models.CharField(max_length=255),
        ),
    ]
