# Generated by Django 5.0.7 on 2024-08-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshops', '0002_booking_customer_booking_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='month',
            field=models.CharField(choices=[('In_Progress', 'In_Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
