# Generated by Django 5.0.7 on 2024-08-10 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carshops', '0003_booking_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='month',
            new_name='booking_status',
        ),
    ]
