# Generated by Django 5.1 on 2024-10-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshops', '0003_alter_booking_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='selected_slot',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
