# Generated by Django 5.1 on 2024-10-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshops', '0004_booking_selected_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='selected_slot',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
