# Generated by Django 5.1 on 2024-10-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshops', '0006_remove_booking_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='driver_response',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
