# Generated by Django 5.0.7 on 2024-08-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshops', '0006_service_car_type_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_type_status',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Hatch_Back', 'Hatch Back')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
