# Generated by Django 5.0.7 on 2024-08-18 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshops', '0008_car_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_type_status',
            new_name='car_type',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('review', models.CharField(max_length=255)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carshops.booking')),
            ],
        ),
    ]
