# Generated by Django 5.0.7 on 2024-08-18 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshops', '0009_rename_car_type_status_car_car_type_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bkservice', to='carshops.service'),
            preserve_default=False,
        ),
    ]
