# Generated by Django 5.1 on 2024-10-05 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshops', '0011_remove_carwashphoto_driver_carwashphoto_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carshop',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carshops', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
