# Generated by Django 5.1 on 2024-10-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshops', '0012_carshop_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
            preserve_default=False,
        ),
    ]
