# Generated by Django 5.1 on 2024-10-06 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshops', '0014_alter_booking_booking_date'),
        ('my_app', '0011_remove_user_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_address', to='my_app.address'),
        ),
    ]
