# Generated by Django 5.1 on 2024-10-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshops', '0016_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('In_Progress', 'In Progress'), ('Completed', 'Completed'), ('On_Way_To_Pickup', 'On Way to Pickup'), ('Cancelled', 'Cancelled')], default='In_Progress', max_length=20),
        ),
    ]
