# Generated by Django 5.1 on 2024-10-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshops', '0017_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='driver_response',
            field=models.CharField(blank=True, default='Pending', max_length=20, null=True),
        ),
    ]
