# Generated by Django 5.1 on 2024-10-14 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carshops', '0022_driverresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverResponse',
        ),
    ]
