# Generated by Django 5.1 on 2024-10-14 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshops', '0023_delete_driverresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='available_drivers',
            field=models.ManyToManyField(blank=True, related_name='available_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
