# Generated by Django 5.1 on 2024-10-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carshops', '0024_booking_available_drivers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='available_drivers',
        ),
    ]
