# Generated by Django 5.1 on 2024-10-14 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshops', '0025_remove_booking_available_drivers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='responded_drivers',
            field=models.ManyToManyField(blank=True, related_name='responded_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('In_Progress', 'In Progress'), ('Completed', 'Completed'), ('Accepted', 'Accepted'), ('On_Way_To_Pickup', 'On Way to Pickup'), ('Cancelled', 'Cancelled')], default='In_Progress', max_length=20),
        ),
    ]
