# Generated by Django 5.1 on 2024-10-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshops', '0026_booking_responded_drivers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='responded_drivers',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('In_Progress', 'In Progress'), ('Completed', 'Completed'), ('On_Way_To_Pickup', 'On Way to Pickup'), ('Cancelled', 'Cancelled')], default='In_Progress', max_length=20),
        ),
    ]
